spring.datasource.url=jdbc:mysql://localhost:3306/CarsavvyProject?serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
jwt.secret=317cb79dd545047d5f1a12a77c4cf9d74ba720eef5aef4a31ccf39a89bf5740d
server.port=8083
logging.level.org.springframework.security=trace